# Site settings
title: Lauchlin Wilkinson
email: contact@lauchlin.com
url: http://www.lauchlin.com/
description: "Portfolio and contact details for Lauchlin Wilkinson."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 5b5c5f #18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: L. Wilkinson 
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: flickr
    url: http://flickr.com/photos/lokulin
  - title: steam
    url: http://steamcommunity.com/id/lokulin/
  - title: bitbucket
    url: http://bitbucket.org/lokulin
  - title: github
    url: http://github.com/lokulin

# Postal address (add as many lines as necessary)
address:
  - line: c/o REA Group, 511 Church St.
  - line: Richmond, Victoria, 3121

# Credits content
credits: 'Based on Freelancer, a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
